import * as THREE from "three";

export const TEXTURE_NAMES: Record<string, string> = {
  bodyshirt: "shirt",
  pant: "pants",
  ear001: "skin",
  hand: "skin",
  neck: "skin",
  plane007: "skin", //face
  shoe: "shoe",
  sole: "sole",
  keys: "keys",
  keys001: "keys",
  keys002: "keys",
  keys003: "keys",
  keys004: "keys",
  keys005: "keys",
  keys006: "keys",
  keys007: "keys",
  keys008: "keys",
  keys009: "keys",
  keys010: "keys",
  keys011: "keys",
  keys012: "keys",
  keys013: "keys",
  keys014: "keys",
  keys015: "keys",
  keys016: "keys",
  keys017: "keys",
  keys018: "keys",
  keys019: "keys",
  keys020: "keys",
  keys021: "keys",
  keys022: "keys",
  keys023: "keys",
  keys024: "keys",
  keys025: "keys",
  keys026: "keys",
  keys027: "keys",
  keys028: "keys",
  keys029: "keys",
  keys030: "keys",
  keys031: "keys",
  keys032: "keys",
  keys033: "keys",
  keys034: "keys",
  keys035: "keys",
  keys036: "keys",
  keys037: "keys",
  keys038: "keys",
  keys039: "keys",
  plane: "chair", //silla
  cube002: "chairLegs", //silla
  plane002: "plane002",
  plane003: "plane003",
};

export const TEXTURES: Record<string, THREE.Texture> = {
  shirt: new THREE.TextureLoader().load("/textures/shirt.png"),
  pants: new THREE.TextureLoader().load("/textures/pants.jpg"),
  skin: new THREE.TextureLoader().load("/textures/skin.jpg"),
  shoe: new THREE.TextureLoader().load("/textures/shoes.jpg"),
  sole: new THREE.TextureLoader().load("/textures/shoes.jpg"),
  keys: new THREE.TextureLoader().load("/textures/keys.jpg"),
  chair: new THREE.TextureLoader().load("/textures/keys.jpg"),
  chairLegs: new THREE.TextureLoader().load("/textures/keys.jpg"),
  plane002: new THREE.TextureLoader().load("/textures/keys.jpg"),
  plane003: new THREE.TextureLoader().load("/textures/keys.jpg"),
};

export const COLORS: Record<string, string> = {
  shirt: "#0077cc",
  pants: "#454545",
  skin: "",
  shoe: "#452B00",
  sole: "#964B00",
  keys: "#c2a4ff",
  chair: "#ccc",
  chairLegs: "#ccc",
  plane002: "#964B00",
  plane003: "#452B00",
};
